# Generated by Django 4.0.3 on 2022-03-15 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_subcategories_mcate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincategories',
            name='image',
        ),
    ]
