# Generated by Django 4.0.3 on 2022-03-16 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_maincategories_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('image', models.ImageField(upload_to='', verbose_name='image/product')),
                ('og_price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('discount_price', models.IntegerField(default=0)),
                ('sell_price', models.IntegerField(default=0)),
                ('ate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.subcategories')),
                ('mte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.maincategories')),
            ],
        ),
    ]
