# Generated by Django 4.0.3 on 2022-03-31 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_customeraddressmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomeraddressModel',
        ),
    ]
